services:
  api:
    build: ./api
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=myuser
      - PG_PASSWORD=mysupersecret
      - PG_DB=analytics
      - MINIO_ENDPOINT=http://minio:9000
    volumes:
      - ./data/files:/data/files
    ports:
      - '9999:9999'

  lakehouse:
    build: ./lakehouse
    depends_on:
      - api
      - minio
      - postgres
      - elasticsearch
    ports:
      - '9870:9870'
      - '8088:8088'
      - '7077:7077'
      - '8000:8000'

  minio:
    build: ./minio
    ports:
      - '9000:9000'
      - '9001:9001'

  postgres:
    build: ./postgres
    ports:
      - '5432:5432'

  elasticsearch:
    build: ./elasticsearch
    ports:
      - '9200:9200'

  prometheus:
    build: ./prometheus
    ports:
      - '9090:9090'

networks:
  default:
    driver: bridge