# Utilise l'image officielle Prometheus comme base
FROM prom/prometheus:latest

# Copie le fichier de configuration Prometheus personnalisé dans le conteneur
COPY prometheus.yml /etc/prometheus/prometheus.yml